/* Automatically generated by po2tbl.sed from howto.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"HOWTOs", 2},
  {"Elément à rechercher", 3},
  {"  Rechercher:  ", 4},
  {"Un des mots", 5},
  {"Tous les mots", 6},
  {"La phrase", 7},
  {"Copyright (c) 2001 - Philippe BOUSQUET", 8},
  {"Logiciel distribué sous la licence GNU GENERAL PUBLIC LICENSE", 9},
  {"Couldn't find pixmap file: %s", 10},
  {"Couldn't create pixmap from file: %s", 11},
};

int _msg_tbl_length = 11;
